# Generated by Django 5.0.7 on 2024-08-20 12:03

import automation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sdk_root', models.CharField(max_length=255)),
                ('service_url', models.URLField()),
                ('booted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='App name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_changed', models.BooleanField(default=False)),
                ('is_tested', models.BooleanField(default=False)),
                ('apk_file_path', models.FileField(upload_to=automation.models.get_upload_path, verbose_name='APK File Path')),
                ('ui_hierarchy', models.FileField(blank=True, null=True, upload_to=automation.models.get_upload_path)),
                ('video_recording_path', models.FileField(blank=True, null=True, upload_to=automation.models.get_upload_path)),
                ('first_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to=automation.models.get_upload_path)),
                ('second_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to=automation.models.get_upload_path)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
